export const CategoryEnum = [
	'Arts and Entertainment',
	'Construction',
	'Consulting',
	'Customer Service',
	'Data Science',
	'Digital Marketing',
	'Education',
	'Finance',
	'Food Service',
	'Freelance',
	'Government',
	'Healthcare',
	'Hospitality',
	'Human Resources',
	'Legal',
	'Non-profit',
	'Operations',
	'Other',
	'Product Management',
	'Research',
	'Retail',
	'Sales',
	'Software Development',
	'Transportation',
	'UI/UX Design',
	'Web Development',
];
